# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title  A Metropolis sampler using Rcpp
#' @description  A Metropolis sampler using Rcpp
#' @param N the number of samples
#' @param x the number of between-sample random number
#' @param sigma variance
#' @return a numericmatrix with a random sample of size \code{n} and k
#' @examples
#' \dontrun{
#' sigma <- 2
#' x <- 25
#' N <- 2000
#' res <- rwc(sigma, x, N)
#' }
#' @useDynLib StatComp20034, .registration = TRUE
#' @exportPattern "^[[:alpha:]]+"
#' @importFrom Rcpp evalCpp
#' @export
rwc <- function(sigma, x, N) {
    .Call(`_StatComp20034_rwc`, sigma, x, N)
}

